### ISSUE TITLE
关于钉钉逆向

### ISSUE THREAD

**Issue by jzp113** [veryyoung/DingDingLuckyMoney#4]
请问下是咋逆向分析的。钉钉好像加壳了。
我准备hook到打卡定位的地址找到具体了类了。一直hook不到

**Comment by veryyoung** [comment]
@jzp113 应该是挺难弄的哈哈，总不能让你随随便便就远程打卡了是吧？

**Comment by guoyoujin** [comment]
你们够狠，这要是都被你搞了，钉钉还有毛用啊，而且现在挺多公司用这玩意打卡。
