### ISSUE TITLE
无法实现自动抢红包

### ISSUE THREAD

**Issue by 1113567888** [veryyoung/DingDingLuckyMoney#5]
down了您的代码，貌似无法实现自动抢钉钉红包

**Comment by veryyoung** [comment]
@1113567888 https://github.com/veryyoung/DingDingLuckyMoney/commit/f94ba78103d51199daeb45a620a4efb3994d4d5e

**Comment by 1113567888** [comment]
我这边还是 无法实现的，我这边钉钉的版本是 3.2.0

**Comment by veryyoung** [comment]
@1113567888 可以的。如果不行的话，可能是您 xposed 的问题吧。

**Comment by 1113567888** [comment]
我是直接使用您的代码，没有改动过。用你那的代码run在手机上，我这时候开启钉钉，发送红包，是不能抢的，或者您有联系方式吗？QQ或者微信，可以和您聊一下

**Comment by veryyoung** [comment]
@1113567888 请问你知道什么是 xposed 吗？

**Comment by 1113567888** [comment]
你说的不是 热修复的一种框架吗？是阿里做的？

**Comment by 1113567888** [comment]
哦 ，估计我弄混了，明白你的意思了

**Comment by 1113567888** [comment]
你的意思 手机要装Xposed插件app 是吧？
