### ISSUE TITLE
新版本不适配3.3.5

### ISSUE THREAD

**Issue by veryold** [veryyoung/DingDingLuckyMoney#9]
多次重启测试 都不好用。。
xp版本2.7
安卓版本4.4.4

**Comment by veryold** [comment]
作者大大 您的机器测试3.3.5没有问题吗  难道我是个例？

**Comment by veryyoung** [comment]
@veryold 我试过了，可以啊。你是发的那啥定时红包吗？定时那个我没搞，企业里面少搞这种严重影响公平的事情。

**Comment by veryyoung** [comment]
@veryold 定时的也适配了。

**Comment by veryold** [comment]
@veryyoung 实验了一下 安卓4.4.4 xp2.7的版本不能领取红包 适配3.3.0那版没问题
刷了cm13 安卓6.01 xp3.1.1 可以正常领取红包了
应该是xp的问题？

**Comment by veryyoung** [comment]
@veryold xp 问题我不管。不属于本软件的范畴。

**Comment by greylucker** [comment]
> 3.3.0

我也是安卓4.4.4  有办法解决怎么都不生效的问题吗
